import Vue from 'vue'
import { Button, Form, FormItem, Input, MenuItem, Menu, Row, Col, Dropdown, DropdownMenu, DropdownItem, PageHeader, Submenu, MenuItemGroup, Divider, Avatar, Upload, Table, TableColumn, Pagination,Breadcrumb,BreadcrumbItem,Card} from 'element-ui'

Vue.use(Button)
.use(Form)
.use(FormItem)
.use(Input)
.use(MenuItem)
.use(Menu)
.use(Row)
.use(Col)
.use(Dropdown)
.use(DropdownItem)
.use(DropdownMenu)
.use(PageHeader)
.use(Submenu)
.use(MenuItemGroup)
.use(Divider)
.use(Avatar)
.use(Upload)
.use(Table)
.use(TableColumn)
.use(Pagination)
.use(Breadcrumb)
.use(BreadcrumbItem)
.use(Card)
